---
title: "Clinical data preparation"
author: Lara Wautier, Celine Bugli, Laura Vermeren, Laura Symul
date: today
format: 
   html:
     page-layout: full
     code-fold: true
     toc: true
     toc-location: left
     toc-depth: 5
     embed-resources: true
execute:
  cache: refresh # true refresh false
  warning: false
knitr:
  opts_chunk:
    out.width: "100%"
editor: source
---

```{r}

library(tidyverse)
library(gt)

```


## Load the data 

```{r}

# will the data be stored on dropbox or onedrive?
# >TODO: adjust the function

OneDrive_dir <- "C:/Users/lvermeren/OneDrive - UCL/VIBRANT clinical data/"

load(str_c(OneDrive_dir, "Data processed/visits.RData"))
crf <- load(str_c(OneDrive_dir, "crf processed/participants_crf_list.RData"))


```


**Data preprocessing**

```{r}


visits <- 
  visits |> 
  mutate_if(is.character, as.factor)


```

## Explanatory & QC analyses

### Sexual activity

```{r}

visits |> 
  ggplot(aes(x = past_week_sex_partner |> fct_rev())) +
  geom_bar(color="darkblue", fill="cornflowerblue") + 
  xlab("Sexual partner of the last week") + 
  ylab("Number of participants") +
  theme_bw() + 
  geom_text(stat = "count", aes(label = ..count..), vjust = -0.5)


visits |> 
  ggplot(aes(x = new_sex_partner |> fct_rev())) +
  geom_bar(color="darkblue", fill="cornflowerblue") + 
  xlab("New sexual partner") + 
  ylab("Number of participants") +
  theme_bw()+
  geom_text(stat = "count", aes(label = ..count..), vjust = -0.5)

visits |> 
  ggplot(aes(x = use_condoms |> fct_rev())) +
  geom_bar(color="darkblue", fill="cornflowerblue") + 
  xlab("Use condoms") + 
  ylab("Number of participants") +
  theme_bw()+
  geom_text(stat = "count", aes(label = ..count..), vjust = -0.5)

visits |> 
  ggplot(aes(x = ability_have_sex |> fct_rev())) +
  geom_bar(color="darkblue", fill="cornflowerblue") + 
  xlab("Ability to have sex") + 
  ylab("Number of participants") +
  theme_bw()+
  geom_text(stat = "count", aes(label = ..count..), vjust = -0.5)

```

Check for incoherent data

```{r}

visits |>
  mutate(
    is_incoherent = case_when(
      
      str_detect(past_week_sex_partner, "no sex") &
        (use_condoms != "not applicable" & use_condoms != "no" |
         !str_detect(new_sex_partner, "no sex") & new_sex_partner != "no") ~ TRUE,
      
      !str_detect(past_week_sex_partner, "no sex") & 
        (use_condoms == "not applicable" | str_detect(new_sex_partner, "no sex")) ~ TRUE,
      
      TRUE ~ FALSE
    )
  ) |>
  filter(is_incoherent) |>
  select(pid, past_week_sex_partner, use_condoms, new_sex_partner) |> 
  gt()


```

**Plot**

We create a table `visits_full` that contains all the visits for each participant. The visits that are not available are filled with `NA` values.

```{r}

visits_crf19_all <-
  expand.grid(
    pid = unique(visits$pid),
    dfseq = c(1000,1100,1200,1300,1400,1500,1700,1900,2120)
  )

visits_full <- visits_crf19_all |>
  mutate(data_available = if_else(paste(pid, dfseq) %in% 
                                    paste(visits$pid, visits$dfseq),
                                  "yes", "no")) |>
  left_join(visits, by = c("pid", "dfseq"))

```

Bleeding

```{r}

visits_full |>
  ggplot(aes(x = dfseq, y = pid |> as.factor())) +
  geom_tile(
    data = subset(visits_full, data_available == "no"),
    fill = "lightgrey",
    color = NA,
    height = 0.8
  ) +
  
  geom_point(aes(color = vaginal_bleeding),alpha = 0.7) +
  
  scale_x_continuous(breaks = c(1000,1100,1200,1300,1400,1500,1700,1900,2120)) +
    
  scale_color_manual(
    name = "Vaginal Bleeding", 
    values = c(
      "no-none" = "transparent",
      "yes-light" = "lightpink",
      "yes-heavy" = "maroon3",
      "D" = "red"
    ),
    na.translate = FALSE
  ) +
  
  labs(x = "Visit Code", y = "Participant ID") +
  theme_bw()
  
  # facet_grid(~arm)

```

Sexual activity

```{r}

visits_full |>
  ggplot(aes(x = dfseq, y = pid |> as.factor())) +
  geom_tile(
    data = subset(visits_full, data_available == "no"),
    fill = "lightgrey",
    color = NA,
    height = 0.8
  ) +
  
  geom_point(aes(color = past_week_sex_partner), alpha = 0.7) +
  
  scale_x_continuous(breaks = c(1000,1100,1200,1300,1400,1500,1700,1900,2120)) + 
    
  scale_color_manual(
    name = "Sexual Activity",
    values = c(
      "no sex in the past week" = "transparent",
      "a single male partner" = "forestgreen",
      "multiple male partners" = "darkgreen", 
      "a single female partner" = "lightblue",
      "multiple female partners" = "blue",
      "both male and female partners" = "mediumspringgreen"
    ),
    na.translate = FALSE
  ) +
  
  labs(x = "Visit Code", y = "Participant ID") +
  theme_bw()
  

```

Try combining the two plots

```{r}

visits_full |> 
  ggplot(aes(x = dfseq, y = pid |> as.factor(), color = vaginal_bleeding, shape = past_week_sex_partner)) +
  geom_point() +
  geom_tile(
    data = subset(visits_full, data_available == "no"),
    fill = "lightgrey",
    color = NA,
    height = 0.8
  ) + 
  scale_color_manual(
    name = "Vaginal Bleeding", 
    values = c(
      "no-none" = "transparent",
      "yes-light" = "lightpink",
      "yes-heavy" = "maroon3",
      "D" = "red"
    ),
    na.translate = FALSE
  ) + 
  theme_bw()

```

```{r}

library(ggnewscale)


visits_full |>
  ggplot(aes(x = dfseq, y = pid |> as.factor())) +
  
  geom_tile(
    data = subset(visits_full, data_available == "no"),
    fill = "lightgrey",
    color = NA,
    height = 0.8
  ) +
  
  geom_point(aes(color = vaginal_bleeding, fill = vaginal_bleeding),alpha = 0.7) +
  scale_color_manual(
    name = "Vaginal Bleeding", 
    values = c(
      "no-none" = "transparent",
      "yes-light" = "lightpink",
      "yes-heavy" = "maroon3",
      "D" = "red"
    ),
    na.translate = FALSE
  ) + 
  
  new_scale_colour() + 
  
  geom_point(aes(shape = "sexual_activity", color = past_week_sex_partner),alpha = 0.7) +
    
  scale_color_manual(
    name = "Sexual Activity",
    values = c(
      "no sex in the past week" = "transparent",
      "a single male partner" = "forestgreen",
      "multiple male partners" = "darkgreen", 
      "a single female partner" = "lightblue",
      "multiple female partners" = "blue",
      "both male and female partners" = "mediumspringgreen"
    ),
    na.translate = FALSE
  ) +
  scale_shape_manual(
    name = "Sexual Activity",
    values = c("sexual_activity" = 17) 
  ) + 
    
   scale_x_continuous(breaks = c(1000,1100,1200,1300,1400,1500,1700,1900,2120)) +
  
  labs(x = "Visit Code", y = "Participant ID") +
  theme_bw()

```

```{r}
ggplot(visits_full, aes(x=dfseq, y = pid |> as.factor())) + 
  geom_tile(
    data = subset(visits_full, data_available == "no"),
    fill = "lightgrey",
    color = NA,
    height = 0.8
  ) +
  geom_point(aes(color = vaginal_bleeding),alpha = 0.7) +
  scale_color_manual(
    name = "Vaginal Bleeding", 
    values = c(
      "no-none" = "transparent",
      "yes-light" = "lightpink",
      "yes-heavy" = "maroon3",
      "D" = "red"
    ),
    na.translate = FALSE
  ) +
  new_scale_color() + 
  geom_point(aes(color = past_week_sex_partner),alpha = 0.7) +
  scale_color_manual(
    name = "Sexual Activity",
    values = c(
      "no sex in the past week" = "transparent",
      "a single male partner" = "forestgreen",
      "multiple male partners" = "darkgreen", 
      "a single female partner" = "lightblue",
      "multiple female partners" = "blue",
      "both male and female partners" = "mediumspringgreen"
    ), 
     na.translate = FALSE
  ) + 
  scale_x_continuous(breaks = c(1000,1100,1200,1300,1400,1500,1700,1900,2120)) + 
  theme_bw()
  
```

