---
title: "VIBRANT Luminex QC - batch 1"
author: Laura Symul
date: today
format: 
   html:
     page-layout: full
     code-fold: true
     toc: true
     toc-location: left
     toc-depth: 5
     embed-resources: true
execute:
  cache: refresh # true
  warning: false
knitr:
  opts_chunk:
    out.width: "100%"
editor: source
---

# Misc

```{r}

tmp_summary <- 
  tmp |> 
  filter(!is.infinite(diff)) |> 
  mutate(
    diff_bin = 
      cut(
        diff, 
        breaks = 
          c(-20, -10, -5, -2.5, -1.25, -0.625, -0.3125, -0.15625,
            0.15625, 0.3125, 0.625, 1.25, 2.5, 5, 10, 20)
        )
  ) |> 
  group_by(.feature, replicate_type, diff_bin) |>
  summarize(n = n(), .groups = "drop") |>
  group_by(.feature, replicate_type) |>
  mutate(f = n/sum(n)) |> 
  ungroup()

```

```{r}

tmp_summary |> 
  ggplot() +
  aes(x = diff_bin |> as.integer(), y = f, col = replicate_type) +
  geom_line() +
  facet_wrap(.feature ~ ., scales = "free") 

```

```{r}
#| fig-height: 15
#| fig-width: 15

plot_pca_scores(pca_res, complete |> filter(sample_type == "Sample"), axes = 1:2, col_by = "visit") +
  scale_color_manual(values = visit_colors) +
  facet_wrap(pid + location ~ .)

plot_pca_scores(pca_res, complete |> filter(sample_type == "Sample"), axes = 2:3, col_by = "visit") +
  scale_color_manual(values = visit_colors) +
  facet_wrap(pid + location ~ .)

plot_pca_scores(pca_res, complete |> filter(sample_type == "Sample"), axes = 4:5, col_by = "visit") +
  scale_color_manual(values = visit_colors) +
  facet_wrap(pid + location ~ .)

```

```{r}
#| fig-height: 15
#| fig-width: 15

raw |> 
  as_tibble()  |> 
  filter(sample_type == "Sample", plate_nb %in% 1:2) |> 
  group_by(sample_id) |> 
  mutate(n_samples = n_distinct(.sample), on_plate_1 = any(plate_nb == 1)) |>
  ungroup() |> 
  filter(n_samples > 1, on_plate_1) |>
  ggplot() +
  aes(x = sample_id, y = conc_log2, col = sample_id) +
  geom_text(aes(label = plate_nb)) +
  guides(col = "none") +
  facet_wrap(.feature ~ ., scales = "free") +
  scale_x_discrete(breaks = NULL) 

```

## Sources of variation

```{r}

tmp <- raw |> as_tibble()

mod <- 
  lm(
    conc_log2 ~ factor(plate_nb) + location + factor(visit_nb) + pid + sample_id + .feature , 
    data = 
      tmp |> 
      filter(sample_type == "Sample", !is.na(conc_log2))
    )

# mod |> summary()

mod |> anova()

```



```{r}

tmp <- raw |> as_tibble()

mod2 <- 
  lm(
    conc_log2_imputed ~ factor(plate_nb) + location + factor(visit_nb) + pid + sample_id + .feature , 
    data = 
      tmp |> 
      filter(sample_type == "Sample", !is.na(conc_log2_imputed))
    )

# mod |> summary()

mod2 |> anova()

```
